package cn.mingyuan.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("department", "id", Department.class);
		arp.addMapping("institution", "id", Institution.class);
		arp.addMapping("permission", "id", Permission.class);
		arp.addMapping("user_info", "id", UserInfo.class);
	}
}

