package cn.mingyuan.model;

import cn.mingyuan.model.base.BaseInstitution;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Institution extends BaseInstitution<Institution> {
	public static final Institution dao = new Institution().dao();
}
