package cn.mingyuan.model;

import cn.mingyuan.model.base.BasePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Permission extends BasePermission<Permission> {
	public static final Permission dao = new Permission().dao();
}
