package cn.mingyuan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserInfo<M extends BaseUserInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public M setDepId(java.lang.Integer depId) {
		set("dep_id", depId);
		return (M)this;
	}

	public java.lang.Integer getDepId() {
		return get("dep_id");
	}

	public M setSysGrade(java.lang.Integer sysGrade) {
		set("sys_grade", sysGrade);
		return (M)this;
	}

	public java.lang.Integer getSysGrade() {
		return get("sys_grade");
	}

	public M setRealName(java.lang.String realName) {
		set("real_name", realName);
		return (M)this;
	}

	public java.lang.String getRealName() {
		return get("real_name");
	}

	public M setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
		return (M)this;
	}

	public java.lang.String getTelephone() {
		return get("telephone");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public M setNote(java.lang.String note) {
		set("note", note);
		return (M)this;
	}

	public java.lang.String getNote() {
		return get("note");
	}

	public M setDeadline(java.util.Date deadline) {
		set("deadline", deadline);
		return (M)this;
	}

	public java.util.Date getDeadline() {
		return get("deadline");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setRole(java.lang.Integer role) {
		set("role", role);
		return (M)this;
	}

	public java.lang.Integer getRole() {
		return get("role");
	}

	public M setSuperView(java.lang.Integer superView) {
		set("super_view", superView);
		return (M)this;
	}

	public java.lang.Integer getSuperView() {
		return get("super_view");
	}

	public M setInstId(java.lang.Integer instId) {
		set("inst_id", instId);
		return (M)this;
	}

	public java.lang.Integer getInstId() {
		return get("inst_id");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
